apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-eks-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/lucifer140/local-agro-test.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: arn:aws:eks:ca-central-1:885300287765:cluster/multiargocd-eks
    namespace: default
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # 

